FROM hub.jdcloud.com/mesh/mesh-telemetry:2.8.1-sec-e7b78d8
#FROM arm64v8/openjdk:11 # for ARM64
MAINTAINER Zhiguo.Chen<chenzhiguo@jd.com>
USER root

ENV TZ Asia/Shanghai

RUN rm -rf /java
RUN yum install -y unzip
