{
 "title": "tpaas-jmsf-nacos-sync",
 "description": "注册中心同步监控",
 "tags": [
  "jmsf",
  "nacos-sync"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "可同步注册中心数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nacosSync_cluster_size" }
   ]
  },
  {
   "title": "同步任务数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nacosSync_task_size" }
   ]
  },
  {
   "title": "每秒添加同步任务数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nacosSync_add_task_rt_seconds_count[5m])"
    }
   ]
  }
 ]
}